name: Issue Welcome

on:
  issues:
    types: [opened]

jobs:
  welcome:
    permissions:
      issues: write
    uses: Mininglamp-OSS/.github/.github/workflows/issue-welcome.yml@e367284d0c052d184d4e625732f840a1f6ed118a
